### ISSUE TITLE
Fix callout edit button in LP to not crash into dropdown arrow.

### ISSUE THREAD

**Issue by sigrunixia** [ebullient/obsidian-theme-ebullientworks#101]
![CleanShot 2024-06-27 at 18 41 44](https://github.com/ebullient/obsidian-theme-ebullientworks/assets/68425372/37f5e521-49e3-436a-b9be-9eedee0c061d)
 This

**Comment by sigrunixia** [comment]
I am thinking of just displaying none this, since it is only a LP issue. 

```css
.markdown-source-view.mod-cm6 .edit-block-button {
    display: none;
}
```

Result is a consistent look with reading view.

![CleanShot 2024-06-27 at 21 22 31](https://github.com/ebullient/obsidian-theme-ebullientworks/assets/68425372/7649d500-fc84-44de-a60d-1e22d5e924c9)


Thumbs up, or Thumbs down, @ebullient?
