### ISSUE TITLE
Dark theme hightlighting text caret-color issue

### ISSUE THREAD

**Issue by emisjerry** [ebullient/obsidian-theme-ebullientworks#5]
Dark theme and editor mode, the cursor caret-color diffcult be seen.
 
![image](https://user-images.githubusercontent.com/131511/143159812-3e3827fa-e1f3-412a-8ac7-7e8450268305.png)

My temporary fix:
```css
.theme-dark .cm-highlight {
  caret-color: var(--text-highlight-fg);
}
```
