### ISSUE TITLE
Fix properties crashing on vertical mobile views

### ISSUE THREAD

**Issue by sigrunixia** [ebullient/obsidian-theme-ebullientworks#99]
![IMG_3041](https://github.com/ebullient/obsidian-theme-ebullientworks/assets/68425372/3a68918b-0a93-4fc0-ae71-ec3acb180d25)

As seen here.
Iphone 11 pro max sized screen.

**Comment by sigrunixia** [comment]
Will remove the properties title up top on mobile

**Comment by sigrunixia** [comment]
Okay, so simple hiding is not.. optimal.


## Option A

![CleanShot 2024-06-27 at 21 40 25](https://github.com/ebullient/obsidian-theme-ebullientworks/assets/68425372/2295f30e-8af1-406b-9598-ca66d3214ff4)


```css
@media screen and (max-width: 700px) {

  .metadata-properties-title {
    margin-bottom: var(--size-4-1);
    padding: var(--size-2-3);
    display: flex;
    justify-content: left;
    font-family: var(--ebw-header-font);
    background-color: rgba(var(--secondary-accent-4-rgb), 0.1);

    &:before {
      display: none;
    }
    &::after {
      display: none;
    }
  }

  .markdown-source-view .metadata-container .metadata-add-button {
    margin-top: revert;
    padding-left: revert;
    position: revert;
    font-size: revert;
    left: revert;
    top: revert;
  }
}
```

**Comment by sigrunixia** [comment]
## Option B

![CleanShot 2024-06-27 at 21 42 25](https://github.com/ebullient/obsidian-theme-ebullientworks/assets/68425372/2ba6fff9-5571-4dda-8f26-8cacfd6dbed9)

```css
@media screen and (max-width: 700px) {

  .metadata-properties-title {
    display: none;
  }

  .markdown-source-view .metadata-container .metadata-add-button {
    margin-top: revert;
    padding-left: revert;
    position: revert;
    font-size: revert;
    left: revert;
    top: revert;
  }
}
```
